{
  config,
  lib,
  pkgs,
  ...
}: {
  ## Declarative disk partitioning (disko)
  #
  # This replaces the fileSystems blocks previously generated by nixos-generate-config
  # (see ./hardware-configuration.nix) with declarative partition + mount definitions.
  #
  # IMPORTANT:
  #   - `nixos-rebuild switch` NEVER touches the disks. disko only acts when explicitly
  #     invoked (e.g. `sudo disko --mode destroy,format,mount --flake .#nixos`), which
  #     WIPES ALL DATA on both disks. Only run that on a fresh install.
  #   - Mounts are generated with device = /dev/disk/by-partlabel/disk-<disk>-<partition>
  #     (stable across reformats, unlike UUIDs).
  #   - / and /nix are automatically mounted from the initrd (NixOS adds x-initrd.mount
  #     for neededForBoot filesystems; boot.initrd.systemd is enabled in ./boot.nix).
  #
  # Layout (mirrors the on-disk geometry exactly, incl. unpartitioned space):
  #
  #   nvme0n1 (476.9G system disk)
  #   ├─ p1  1M - 1251M        ESP, vfat        -> /boot/efi
  #   ├─ p4  1251M - 2501M     ext4 /boot       -> /boot   (physically 2nd, partition number 4)
  #   ├─ p2  2501M - 156500M   btrfs "root"     -> subvolumes: @ -> /, nix -> /nix, swap -> /swap
  #   ├─ p3  156500M - 457862M btrfs "nix-home" -> /home (top-level default subvol)
  #   └─ ~29.8G unpartitioned trailing space
  #
  #   sda (447.1G data disk)
  #   ├─ 2500M unpartitioned gap at start of disk
  #   ├─ p1  2501M - 207501M   btrfs "LFS"     -> /user/lfs  (noauto)
  #   ├─ p2  207501M - 452502M btrfs "Data"    -> /user/data (noauto)
  #   └─ ~5.2G unpartitioned trailing space
  #
  # Swap: the 32G swapfile lives in the `swap` subvolume (mounted at /swap) and is
  # created/managed by NixOS via swapDevices in ./swap.nix - intentionally NOT by disko,
  # so swap.nix stays the single source of truth for swap.

  disko.devices = {
    disk = {
      nvme0n1 = {
        type = "disk";
        device = "/dev/nvme0n1";
        content = {
          type = "gpt";
          partitions = {
            esp = {
              start = "1MiB"; # sector 2048
              end = "1251MiB";
              type = "EF00"; # EFI System Partition
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot/efi";
                mountOptions = [
                  "fmask=0077"
                  "dmask=0077"
                ];
              };
            };

            boot = {
              start = "1251MiB";
              end = "2501MiB";
              type = "0700"; # "Microsoft basic data" - matches current (quirky) layout
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/boot";
                mountOptions = [
                  "defaults"
                  "noatime"
                ];
              };
            };

            root = {
              start = "2501MiB";
              end = "156500MiB";
              content = {
                type = "btrfs";
                extraArgs = ["-f"];
                subvolumes = {
                  "/@" = {
                    mountpoint = "/"; # subvol=@
                    mountOptions = ["compress=zstd"];
                  };
                  "/nix" = {
                    mountpoint = "/nix";
                    mountOptions = [
                      "compress=zstd"
                      "noatime"
                    ];
                  };
                  "/swap" = {
                    mountpoint = "/swap";
                    mountOptions = ["noatime"];
                  };
                };
              };
            };

            home = {
              start = "156500MiB";
              end = "457862MiB";
              type = "8302"; # Linux home
              content = {
                type = "filesystem";
                format = "btrfs";
                mountpoint = "/home"; # no subvol -> mounts top-level (subvolid=5), as today
                mountOptions = ["compress=zstd"];
              };
            };
          };
        };
      };

      sda = {
        type = "disk";
        device = "/dev/sda";
        content = {
          type = "gpt";
          partitions = {
            lfs = {
              start = "2501MiB"; # 2500MiB unpartitioned gap at start of disk (matches current layout)
              end = "207501MiB";
              content = {
                type = "filesystem";
                format = "btrfs";
                mountpoint = "/user/lfs";
                mountOptions = [
                  "noauto"
                  "nofail"
                  "noexec"
                  "users"
                ];
              };
            };

            data = {
              start = "207501MiB";
              end = "452502MiB";
              content = {
                type = "filesystem";
                format = "btrfs";
                mountpoint = "/user/data";
                mountOptions = [
                  "noauto"
                  "nofail"
                  "noexec"
                  "users"
                ];
              };
            };
          };
        };
      };
    };
  };

  ## Garbage collection
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };

  ## Nix store optimisation on every build
  nix.settings.auto-optimise-store = true;

  ## Auto clean /tmp on boot
  boot.tmp.cleanOnBoot = true;

  ## BTRFS optimizations

  ## Scrubbing
  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly"; # Reduced from weekly for less I/O interference
  };

  ## Deduping
  # NOTE:
  # run dedupe per subvolume, not on entire filesystem
  # Also, always (if doing so) defragment *before* deduping
  # WARNING:
  # DO NOT dedupe /nix/store and /boot, and use CAUTION while deduping /var

  ## Beesd
  services.beesd.filesystems = {
    root = {
      # spec = "LABEL=root"; # or "/dev/disk/by-uuid/..." or subvol path
      spec = "/"; # mount point
      hashTableSizeMB = 128; # ~128MiB per TiB of data
      verbosity = "crit";
      extraOptions = [
        "--thread-count=2"
        "--loadavg-target"
        "2.0"
      ];
    };
    home = {
      # spec = "LABEL=nix-home";
      spec = "/home";
      hashTableSizeMB = 128;
      verbosity = "crit";
      extraOptions = [
        "--thread-count=2"
        "--loadavg-target"
        "2.0"
      ];
    };
  };
  ## To disable autostart, run the following for each filesystem
  systemd.services."beesd@root".wantedBy = lib.mkForce [];
  systemd.services."beesd@home".wantedBy = lib.mkForce [];
  ## Start manually by running: systemctl start beesd@<filesystem>

  ## Duperemove
  # 1. Check status
  # # sudo btrfs scrub status /home
  # 2. Dry run
  # # sudo duperemove -r -d -h --hashfile=/var/lib/duperemove-home.hash /home
  # 3. Dedupe
  # # sudo duperemove -r --limit=2G -h --hashfile=/var/lib/duperemove-home.hash /home
  environment.systemPackages = with pkgs; [
    duperemove
    bees

    # APFS tools
    apfs-fuse
    apfsprogs
  ];

  ## Gaming specialization: disable BTRFS scrub during gaming
  specialisation = {
    gaming.configuration = {
      services.btrfs.autoScrub.enable = lib.mkForce false;
    };
  };
}
